<?php

namespace Database\Seeders;

use App\Models\Question;
use App\Models\Quiz;
use Illuminate\Database\Seeder;

class ClassroomQuizSeeder extends Seeder
{
    public function run(): void
    {
        $quizzes = $this->getSeededQuizzes();

        foreach ($quizzes as $quizData) {
            $quiz = Quiz::firstOrCreate(
                ['id' => $quizData['id']],
                [
                    'title' => $quizData['title'],
                    'description' => $quizData['description'],
                    'subject' => $quizData['subject'],
                    'class_name' => $quizData['class_name'],
                    'duration' => $quizData['duration'],
                    'passing_score' => $quizData['passing_score'],
                    'shuffle_questions' => $quizData['shuffle_questions'],
                    'status' => 'published',
                    'due_date' => now()->addDays(30),
                ]
            );

            if ($quiz->wasRecentlyCreated && ! empty($quizData['questions'])) {
                foreach ($quizData['questions'] as $questionData) {
                    Question::create([
                        'id' => $questionData['id'],
                        'quiz_id' => $quiz->id,
                        'question_text' => $questionData['question_text'],
                        'question_type' => $questionData['question_type'],
                        'points' => $questionData['points'],
                        'choices' => $questionData['choices'] ?? [],
                        'correct_answer' => $questionData['correct_answer'] ?? '',
                        'order' => $questionData['order'],
                    ]);
                }
            }
        }
    }

    private function getSeededQuizzes(): array
    {
        return [
            // 1. Present Simple Tense
            [
                'id' => 'seed-present-simple',
                'title' => 'Present Simple Tense',
                'description' => 'Test your knowledge of the Present Simple tense in English grammar.',
                'subject' => 'English',
                'class_name' => 'Grade 10',
                'duration' => 10,
                'passing_score' => 50,
                'shuffle_questions' => true,
                'questions' => [
                    [
                        'id' => 'ps-1',
                        'question_text' => 'She ___ to school every day.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'go', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'goes', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'going', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'went', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 1,
                    ],
                    [
                        'id' => 'ps-2',
                        'question_text' => 'They ___ playing football in the park.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'is', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'am', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'are', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'be', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 2,
                    ],
                    [
                        'id' => 'ps-3',
                        'question_text' => 'He ___ breakfast at 7 AM every morning.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'have', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'has', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'having', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'had', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 3,
                    ],
                    [
                        'id' => 'ps-4',
                        'question_text' => 'We ___ our teeth every night.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'brush', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => 'brushes', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'brushing', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'brushed', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a',
                        'order' => 4,
                    ],
                    [
                        'id' => 'ps-5',
                        'question_text' => 'The sun ___ in the east.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'rise', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'rises', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'rising', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'rose', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 5,
                    ],
                    [
                        'id' => 'ps-6',
                        'question_text' => '___ you like ice cream?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Does', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Do', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Are', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Is', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 6,
                    ],
                    [
                        'id' => 'ps-7',
                        'question_text' => 'My mother ___ delicious cakes.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'bake', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'bakes', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'baking', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'baked', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 7,
                    ],
                    [
                        'id' => 'ps-8',
                        'question_text' => 'The Earth ___ around the Sun.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'go', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'goes', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'going', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'went', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 8,
                    ],
                    [
                        'id' => 'ps-9',
                        'question_text' => 'I ___ a shower every morning.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'take', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => 'takes', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'taking', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'took', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a',
                        'order' => 9,
                    ],
                    [
                        'id' => 'ps-10',
                        'question_text' => 'Cats ___ milk.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'like', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => 'likes', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'liking', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'liked', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a',
                        'order' => 10,
                    ],
                ],
            ],

            // 2. Past Tense
            [
                'id' => 'seed-past-tense',
                'title' => 'Past Tense',
                'description' => 'Test your knowledge of the Past Simple tense in English.',
                'subject' => 'English',
                'class_name' => 'Grade 10',
                'duration' => 10,
                'passing_score' => 50,
                'shuffle_questions' => true,
                'questions' => [
                    [
                        'id' => 'pt-1',
                        'question_text' => 'She ___ to the store yesterday.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'go', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'goes', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'went', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'gone', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 1,
                    ],
                    [
                        'id' => 'pt-2',
                        'question_text' => 'They ___ a movie last night.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'watch', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'watched', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'watching', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'watches', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 2,
                    ],
                    [
                        'id' => 'pt-3',
                        'question_text' => 'He ___ his keys this morning.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'lose', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'loses', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'lost', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'losing', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 3,
                    ],
                    [
                        'id' => 'pt-4',
                        'question_text' => 'We ___ a great time at the party.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'have', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'has', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'had', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'having', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 4,
                    ],
                    [
                        'id' => 'pt-5',
                        'question_text' => 'The birds ___ away.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'fly', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'flies', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'flew', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'flown', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 5,
                    ],
                    [
                        'id' => 'pt-6',
                        'question_text' => 'She ___ a beautiful dress.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'wear', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'wears', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'wore', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'wearing', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 6,
                    ],
                    [
                        'id' => 'pt-7',
                        'question_text' => 'I ___ him at the station.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'meet', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'meets', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'met', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'meeting', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 7,
                    ],
                    [
                        'id' => 'pt-8',
                        'question_text' => 'They ___ a new car last week.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'buy', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'buys', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'bought', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'buying', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 8,
                    ],
                    [
                        'id' => 'pt-9',
                        'question_text' => 'He ___ a letter to his friend.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'write', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'writes', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'wrote', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'written', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 9,
                    ],
                    [
                        'id' => 'pt-10',
                        'question_text' => 'We ___ breakfast at 8 AM.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'eat', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'eats', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'ate', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'eating', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 10,
                    ],
                ],
            ],

            // 3. Continuous Tenses
            [
                'id' => 'seed-continuous-tenses',
                'title' => 'Continuous Tenses',
                'description' => 'Test your understanding of Present, Past, and Future Continuous tenses.',
                'subject' => 'English',
                'class_name' => 'Grade 10',
                'duration' => 10,
                'passing_score' => 50,
                'shuffle_questions' => true,
                'questions' => [
                    [
                        'id' => 'ct-1',
                        'question_text' => 'She ___ (currently + read) a book.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'reads', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'is reading', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'read', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'was reading', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 1,
                    ],
                    [
                        'id' => 'ct-2',
                        'question_text' => 'They ___ (play) football at 3 PM yesterday.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'play', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'are playing', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'were playing', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'played', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 2,
                    ],
                    [
                        'id' => 'ct-3',
                        'question_text' => 'I ___ (wait) for the bus right now.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'wait', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'am waiting', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'was waiting', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'waited', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 3,
                    ],
                    [
                        'id' => 'ct-4',
                        'question_text' => 'He ___ (cook) dinner when I arrived.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'cooks', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'is cooking', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'was cooking', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'cooked', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 4,
                    ],
                    [
                        'id' => 'ct-5',
                        'question_text' => 'We ___ (travel) to Paris next week.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'travel', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'are traveling', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'traveled', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'were traveling', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 5,
                    ],
                    [
                        'id' => 'ct-6',
                        'question_text' => 'The kids ___ (sleep) at 10 PM last night.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'sleep', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'are sleeping', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'were sleeping', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'slept', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 6,
                    ],
                    [
                        'id' => 'ct-7',
                        'question_text' => 'She ___ (study) for her exams these days.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'studies', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'is studying', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'studied', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'was studying', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 7,
                    ],
                    [
                        'id' => 'ct-8',
                        'question_text' => 'I ___ (work) on a project when you called.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'work', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'am working', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'was working', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'worked', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 8,
                    ],
                    [
                        'id' => 'ct-9',
                        'question_text' => 'They ___ (build) a new school in our area.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'build', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'are building', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'built', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'were building', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 9,
                    ],
                    [
                        'id' => 'ct-10',
                        'question_text' => 'He ___ (watch) TV at the moment.',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'watches', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'is watching', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'watched', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'was watching', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 10,
                    ],
                ],
            ],

            // 4. Basic English Essentials
            [
                'id' => 'seed-basic-english',
                'title' => 'Basic English Essentials',
                'description' => 'Test your basic English vocabulary and grammar fundamentals.',
                'subject' => 'English',
                'class_name' => 'Grade 10',
                'duration' => 10,
                'passing_score' => 50,
                'shuffle_questions' => true,
                'questions' => [
                    [
                        'id' => 'be-1',
                        'question_text' => 'What is the opposite of "hot"?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Warm', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Cold', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Cool', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Freezing', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 1,
                    ],
                    [
                        'id' => 'be-2',
                        'question_text' => 'Choose the correct sentence:',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'He don\'t like coffee.', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'He doesn\'t likes coffee.', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'He doesn\'t like coffee.', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'He not like coffee.', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 2,
                    ],
                    [
                        'id' => 'be-3',
                        'question_text' => 'What is the plural of "child"?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Childs', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Childes', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Children', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Childrens', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 3,
                    ],
                    [
                        'id' => 'be-4',
                        'question_text' => 'Which word is a preposition?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Quickly', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Under', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Beautiful', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Run', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 4,
                    ],
                    [
                        'id' => 'be-5',
                        'question_text' => 'Complete: "I have ___ apple."',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'a', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'an', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'the', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'some', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 5,
                    ],
                    [
                        'id' => 'be-6',
                        'question_text' => 'What does "happy" mean?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Sad', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Angry', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Joyful', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Tired', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 6,
                    ],
                    [
                        'id' => 'be-7',
                        'question_text' => 'Which is a greeting?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Goodbye', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Hello', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Sorry', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Please', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 7,
                    ],
                    [
                        'id' => 'be-8',
                        'question_text' => 'Complete: "She is ___ than her sister."',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'tall', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'taller', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'tallest', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'more tall', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 8,
                    ],
                    [
                        'id' => 'be-9',
                        'question_text' => 'Which word is a pronoun?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'House', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'She', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Jump', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Blue', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 9,
                    ],
                    [
                        'id' => 'be-10',
                        'question_text' => 'Complete: "There ___ many books on the table."',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'is', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'are', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'am', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'be', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 10,
                    ],
                ],
            ],

            // 5. Basic Computer Usage
            [
                'id' => 'seed-basic-computer',
                'title' => 'Basic Computer Usage',
                'description' => 'Test your knowledge of basic computer concepts and operations.',
                'subject' => 'Computer Science',
                'class_name' => 'Grade 10',
                'duration' => 10,
                'passing_score' => 50,
                'shuffle_questions' => true,
                'questions' => [
                    [
                        'id' => 'bc-1',
                        'question_text' => 'What does CPU stand for?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Central Processing Unit', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => 'Computer Personal Unit', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Central Program Unit', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Core Processing Unit', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a',
                        'order' => 1,
                    ],
                    [
                        'id' => 'bc-2',
                        'question_text' => 'Which device is used to store data permanently?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'RAM', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Hard Drive', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Processor', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Monitor', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 2,
                    ],
                    [
                        'id' => 'bc-3',
                        'question_text' => 'What is the main function of an operating system?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Browse the internet', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Manage hardware and software resources', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Create documents', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Play games', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 3,
                    ],
                    [
                        'id' => 'bc-4',
                        'question_text' => 'Which key combination is used to copy text?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Ctrl+X', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Ctrl+V', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Ctrl+C', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Ctrl+Z', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 4,
                    ],
                    [
                        'id' => 'bc-5',
                        'question_text' => 'What is a browser used for?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Writing code', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Editing photos', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Accessing the internet', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Playing music', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 5,
                    ],
                    [
                        'id' => 'bc-6',
                        'question_text' => 'What does "www" stand for?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'World Wide Web', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => 'Web World Wide', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'World Web Wide', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Wide World Web', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a',
                        'order' => 6,
                    ],
                    [
                        'id' => 'bc-7',
                        'question_text' => 'Which of these is an input device?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Monitor', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Printer', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Keyboard', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Speaker', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 7,
                    ],
                    [
                        'id' => 'bc-8',
                        'question_text' => 'What is a computer virus?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'A hardware problem', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'A malicious software', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'A type of computer', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'A storage device', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 8,
                    ],
                    [
                        'id' => 'bc-9',
                        'question_text' => 'What is the function of a firewall?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Speed up the computer', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Protect against unauthorized access', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Store files', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Display graphics', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 9,
                    ],
                    [
                        'id' => 'bc-10',
                        'question_text' => 'Which file extension indicates an executable file?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => '.txt', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => '.jpg', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => '.exe', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => '.doc', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 10,
                    ],
                ],
            ],

            // 6. Logic Puzzles
            [
                'id' => 'seed-logic-puzzles',
                'title' => 'Logic Puzzles',
                'description' => 'Challenge your logical thinking with these puzzles.',
                'subject' => 'Logic',
                'class_name' => 'Grade 10',
                'duration' => 15,
                'passing_score' => 50,
                'shuffle_questions' => true,
                'questions' => [
                    [
                        'id' => 'lp-1',
                        'question_text' => 'If all cats are animals, and some animals are pets, which is true?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'All cats are pets', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Some animals are cats', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'All pets are cats', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'No cats are pets', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 1,
                    ],
                    [
                        'id' => 'lp-2',
                        'question_text' => 'Which number comes next: 2, 4, 6, 8, ?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => '9', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => '10', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => '12', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => '7', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 2,
                    ],
                    [
                        'id' => 'lp-3',
                        'question_text' => 'If today is Monday, what day will it be in 10 days?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Tuesday', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Wednesday', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Thursday', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Friday', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 3,
                    ],
                    [
                        'id' => 'lp-4',
                        'question_text' => 'A bat and a ball cost $1.10. The bat costs $1.00 more than the ball. How much does the ball cost?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => '$0.10', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => '$0.05', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => '$0.20', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => '$0.15', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 4,
                    ],
                    [
                        'id' => 'lp-5',
                        'question_text' => 'Which word does not belong? Apple, Banana, Carrot, Grape',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Apple', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Banana', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Carrot', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Grape', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 5,
                    ],
                    [
                        'id' => 'lp-6',
                        'question_text' => 'Complete the analogy: Bird is to Fly as Fish is to ___',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Swim', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => 'Walk', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Jump', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Crawl', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a',
                        'order' => 6,
                    ],
                    [
                        'id' => 'lp-7',
                        'question_text' => 'If you rearrange the letters "CIFAIPC", you get the name of a(n):',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'City', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Country', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Ocean', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Animal', 'is_correct' => false],
                        ],
                        'correct_answer' => 'd',
                        'order' => 7,
                    ],
                    [
                        'id' => 'lp-8',
                        'question_text' => 'Which is the odd one out? 2, 3, 5, 7, 11, 13, 17',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => '2', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => '3', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => '5', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'None, all are prime numbers', 'is_correct' => false],
                        ],
                        'correct_answer' => 'd',
                        'order' => 8,
                    ],
                    [
                        'id' => 'lp-9',
                        'question_text' => 'A farmer has 15 sheep. All but 8 run away. How many are left?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => '7', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => '8', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => '15', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => '23', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 9,
                    ],
                    [
                        'id' => 'lp-10',
                        'question_text' => 'If it takes 5 minutes to boil 1 egg, how long does it take to boil 3 eggs?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => '5 minutes', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => '10 minutes', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => '15 minutes', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => '20 minutes', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a',
                        'order' => 10,
                    ],
                ],
            ],

            // 7. Challenge Quiz
            [
                'id' => 'seed-challenge-quiz',
                'title' => 'Challenge Quiz',
                'description' => 'A challenging quiz testing various subjects and skills.',
                'subject' => 'General Knowledge',
                'class_name' => 'Grade 10',
                'duration' => 15,
                'passing_score' => 60,
                'shuffle_questions' => true,
                'questions' => [
                    [
                        'id' => 'cq-1',
                        'question_text' => 'What is the chemical symbol for water?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'H2O', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => 'CO2', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'NaCl', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'O2', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a',
                        'order' => 1,
                    ],
                    [
                        'id' => 'cq-2',
                        'question_text' => 'Which planet is known as the Red Planet?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Venus', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Mars', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Jupiter', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Saturn', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 2,
                    ],
                    [
                        'id' => 'cq-3',
                        'question_text' => 'What is the largest ocean in the world?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Atlantic Ocean', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Indian Ocean', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Pacific Ocean', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Arctic Ocean', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 3,
                    ],
                    [
                        'id' => 'cq-4',
                        'question_text' => 'Solve for x: 2x + 5 = 15',
                        'question_type' => 'short_answer',
                        'points' => 10,
                        'choices' => [],
                        'correct_answer' => '5',
                        'order' => 4,
                    ],
                    [
                        'id' => 'cq-5',
                        'question_text' => 'Who wrote "Romeo and Juliet"?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Charles Dickens', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'William Shakespeare', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Jane Austen', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Mark Twain', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 5,
                    ],
                    [
                        'id' => 'cq-6',
                        'question_text' => 'What is the speed of light approximately?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => '300,000 km/s', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => '150,000 km/s', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => '500,000 km/s', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => '100,000 km/s', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a',
                        'order' => 6,
                    ],
                    [
                        'id' => 'cq-7',
                        'question_text' => 'Which country has the largest population?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'USA', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'China', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'India', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Indonesia', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 7,
                    ],
                    [
                        'id' => 'cq-8',
                        'question_text' => 'What is the smallest prime number?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => '0', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => '1', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => '2', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => '3', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 8,
                    ],
                    [
                        'id' => 'cq-9',
                        'question_text' => 'Select all that are programming languages:',
                        'question_type' => 'multiple_answer',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Python', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => 'HTML', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'JavaScript', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'CSS', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a,c',
                        'order' => 9,
                    ],
                    [
                        'id' => 'cq-10',
                        'question_text' => 'The Earth is flat. True or False?',
                        'question_type' => 'true_false',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'true', 'choice_text' => 'True', 'is_correct' => false],
                            ['id' => 'false', 'choice_text' => 'False', 'is_correct' => true],
                        ],
                        'correct_answer' => 'false',
                        'order' => 10,
                    ],
                ],
            ],

            // 8. Basic Algorithms
            [
                'id' => 'seed-basic-algorithms',
                'title' => 'Basic Algorithms',
                'description' => 'Test your understanding of basic algorithms and data structures.',
                'subject' => 'Computer Science',
                'class_name' => 'Grade 10',
                'duration' => 15,
                'passing_score' => 50,
                'shuffle_questions' => true,
                'questions' => [
                    [
                        'id' => 'ba-1',
                        'question_text' => 'What is the time complexity of binary search?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'O(n)', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'O(log n)', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'O(n²)', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'O(1)', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 1,
                    ],
                    [
                        'id' => 'ba-2',
                        'question_text' => 'Which data structure uses LIFO principle?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Queue', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Stack', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Array', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Linked List', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 2,
                    ],
                    [
                        'id' => 'ba-3',
                        'question_text' => 'What is a base case in recursion?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'The first recursive call', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'The condition that stops recursion', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'The recursive function name', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'The last recursive call', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 3,
                    ],
                    [
                        'id' => 'ba-4',
                        'question_text' => 'Which sorting algorithm has the best average time complexity?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Bubble Sort', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Selection Sort', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Merge Sort', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Insertion Sort', 'is_correct' => false],
                        ],
                        'correct_answer' => 'c',
                        'order' => 4,
                    ],
                    [
                        'id' => 'ba-5',
                        'question_text' => 'What does SQL stand for?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Simple Query Language', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Structured Query Language', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Standard Query Language', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Syntax Query Language', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 5,
                    ],
                    [
                        'id' => 'ba-6',
                        'question_text' => 'What is the main purpose of an algorithm?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'To store data', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'To solve a problem step by step', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'To display output', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'To connect to internet', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 6,
                    ],
                    [
                        'id' => 'ba-7',
                        'question_text' => 'Which data structure is used for implementing a queue?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Stack', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'Array', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'Tree', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Graph', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 7,
                    ],
                    [
                        'id' => 'ba-8',
                        'question_text' => 'What is the concept of "divide and conquer"?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Breaking a problem into smaller subproblems', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => 'Combining multiple solutions', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Ignoring complex parts', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'Solving problems randomly', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a',
                        'order' => 8,
                    ],
                    [
                        'id' => 'ba-9',
                        'question_text' => 'Which of these is a machine learning algorithm?',
                        'question_type' => 'multiple_answer',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'Linear Regression', 'is_correct' => true],
                            ['id' => 'b', 'choice_text' => 'Bubble Sort', 'is_correct' => false],
                            ['id' => 'c', 'choice_text' => 'Decision Tree', 'is_correct' => true],
                            ['id' => 'd', 'choice_text' => 'Binary Search', 'is_correct' => false],
                        ],
                        'correct_answer' => 'a,c',
                        'order' => 9,
                    ],
                    [
                        'id' => 'ba-10',
                        'question_text' => 'In programming, what is a variable?',
                        'question_type' => 'multiple_choice',
                        'points' => 10,
                        'choices' => [
                            ['id' => 'a', 'choice_text' => 'A fixed value', 'is_correct' => false],
                            ['id' => 'b', 'choice_text' => 'A container for storing data', 'is_correct' => true],
                            ['id' => 'c', 'choice_text' => 'A type of loop', 'is_correct' => false],
                            ['id' => 'd', 'choice_text' => 'A function', 'is_correct' => false],
                        ],
                        'correct_answer' => 'b',
                        'order' => 10,
                    ],
                ],
            ],
        ];
    }
}
